### ISSUE TITLE
Breaking change in _parameters_ breaks _psycModel_

### ISSUE THREAD

**Issue by strengejacke** [jasonmoy28/psycModel#12]
For consistency reasons, we plan to move the `check_*()` functions from package _parameters_ to _performance_ (see https://github.com/easystats/parameters/issues/581).

We're working on this feature in [this PR](https://github.com/easystats/parameters/pull/777) and realized that this change will break your package. Luckily, the fix is rather easy: once _performance_ is on CRAN (which is planned to be submitted immediately after _parameters_), you just need to do a minor change in this line:
https://github.com/jasonmoy28/psycModel/blob/a0742266dc44a3607821e5d1e67ed61690df3f9c/R/efa_summary.R#L74

Simply change

```r
factor_structure_test <- parameters::check_factorstructure(data)
```

to 

```r
factor_structure_test <- performance::check_factorstructure(data)
```

My question is, if and when you would be able to submit a fix for your package to CRAN? I'd like to coordinate the next steps depending on your availability, to avoid any inconvenience for you getting under pressure due to CRAN submission deadlines...

**Comment by jasonmoy28** [comment]
Hi Daniel,
Thank you for letting me know. It appears that the performance package currently does not have the check_factorstructure function. I assume that it will be available after the performance package updated. Thanks!

Best,

Jason

**Comment by strengejacke** [comment]
Yes, that's right. We would submit _parameters_ (which will break _performance_ and _psycModel_), and then immediately submit _performance_, and once _performance_ is on CRAN, you should be able to submit your update. Currently, since another package is affected, we plan to submit roughly around 7-10th October. Is that OK for you?

**Comment by strengejacke** [comment]
_performance 0.10.0_ is on CRAN. It would be great if you could make the proposed change suggested in the initial post above and submit your package to CRAN. Would you be able to do this the next days? Then we can submit our _parameters_ package without breaking your package during submission.

**Comment by jasonmoy28** [comment]
Hi Daniel,
Thanks for the update. I have already released a new version of my package with the changes. Really appreciate your help in coordinating this.

Best,

Jason

**Comment by strengejacke** [comment]
Thanks a lot!
